export const REQUEST_SUBJECT_PENDING = 'REQUEST_SUBJECT_PENDING';
export const REQUEST_SUBJECT_SUCCESS = 'REQUEST_SUBJECT_SUCCESS';
export const REQUEST_SUBJECT_FAILURE = 'REQUEST_SUBJECT_FAILURE';

export const REQUEST_LIST_PENDING = 'REQUEST_LIST_PENDING';
export const REQUEST_LIST_SUCCESS = 'REQUEST_LIST_SUCCESS';
export const REQUEST_LIST_FAILURE = 'REQUEST_LIST_FAILURE';

export const REQUEST_BOOK_INFO_PENDING = 'REQUEST_BOOK_INFO_PENDING';
export const REQUEST_BOOK_INFO_SUCCESS = 'REQUEST_BOOK_INFO_SUCCESS';
export const REQUEST_BOOK_INFO_FAILURE = 'REQUEST_BOOK_INFO_FAILURE';
