export default {

  FETCH_SUBJECT_LIST: 'FETCH_SUBJECT_LIST',
  FETCH_SUBJECT_LIST_SUCCESS: 'FETCH_SUBJECT_LIST_SUCCESS',
  SUBJECT_SELECTED: 'SUBJECT_SELECTED',

  FETCH_BOOK_LIST: 'FETCH_BOOK_LIST',
  FETCH_BOOK_LIST_SUCCESS: 'FETCH_BOOK_LIST_SUCCESS',
  RESET_BOOK_SELECTION: 'RESET_BOOK_SELECTION',
  BOOK_SELECTED: 'BOOK_SELECTED',
  BOOK_UPDATED: 'BOOK_UPDATED',

  BOOK_ITEM_FORM_FIELD_CHANGE: 'BOOK_ITEM_FORM_FIELD_CHANGE',

};
